on: deployment_status
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      a: ${{ steps.filter.outputs.a }}
      b: ${{ steps.filter.outputs.b }}
    steps:
      - name: Print event
        run: |
          echo "Event name: ${{ github.context.event_name }}"
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Needed to get previous commit on the branch
      - name: Get current and previous commit SHAs
        id: commits
        run: |
          echo "current=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "previous=$(git rev-parse HEAD^)" >> $GITHUB_OUTPUT
      - name: Paths Filter (dorny/paths-filter)
        id: filter
        uses: dorny/paths-filter@v3
        with:
          base: ${{ steps.commits.outputs.previous }}
          ref: ${{ steps.commits.outputs.current }}
          filters: |
            a:
              - 'a/**'
            b:
              - 'b/**'
      - name: Print changed files
        run: |
          echo "Changed in 'a': ${{ steps.filter.outputs.a }}"
          echo "Changed in 'b': ${{ steps.filter.outputs.b }}"
  job-a:
    needs: changes
    if: ${{ needs.changes.outputs.a == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "A"

  job-b:
    needs: changes
    if: ${{ needs.changes.outputs.b == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "B"
