on: deployment_status
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      a: ${{ steps.filter.outputs.a }}
      b: ${{ steps.filter.outputs.b }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get base commit
        id: base
        run: |
          git fetch origin main
          if git merge-base --is-ancestor HEAD origin/main; then
            echo "On main"
            BASE=$(git rev-parse HEAD^)
          else
            echo "On branch"
            BASE=$(git merge-base HEAD origin/main)
          fi
          echo "BASE: $BASE"
          echo "base_commit=$BASE" >> $GITHUB_OUTPUT
      - name: Paths Filter (dorny/paths-filter)
        id: filter
        uses: dorny/paths-filter@v3
        with:
          base: ${{ steps.base.outputs.base_commit }}
          ref: ${{ github.sha }}
          filters: |
            a:
              - 'a/**'
            b:
              - 'b/**'
      - name: Print changed files
        run: |
          echo "Changed in 'a': ${{ steps.filter.outputs.a }}"
          echo "Changed in 'b': ${{ steps.filter.outputs.b }}"
  job-a:
    needs: changes
    if: ${{ needs.changes.outputs.a == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "A"

  job-b:
    needs: changes
    if: ${{ needs.changes.outputs.b == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "B"
