on: push
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          base: main
          filters: |
            a:
              - 'a/**'
            b:
              - 'b/**'
  job-a:
    needs: changes
    if: ${{ needs.changes.outputs.a == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "A"

  job-b:
    needs: changes
    if: ${{ needs.changes.outputs.b == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "B"
