on: deployment_status
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      a: ${{ steps.filter.outputs.a }}
      b: ${{ steps.filter.outputs.b }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get current and base commit SHAs
        id: commits
        run: |
          echo "current=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          # GITHUB_REF may be refs/heads/<branch> or refs/tags/<tag>
          branch="${GITHUB_REF#refs/heads/}"
          if [ "$branch" = "$GITHUB_REF" ]; then
            # Not a branch ref, fallback to extracting last part
            branch="${GITHUB_REF##*/}"
          fi
          if [ "$branch" = "main" ]; then
            echo "base=$(git rev-parse HEAD^)" >> $GITHUB_OUTPUT
          else
            base_commit=$(git merge-base origin/main HEAD)
            echo "base=$base_commit" >> $GITHUB_OUTPUT
          fi
      - name: Paths Filter (dorny/paths-filter)
        id: filter
        uses: dorny/paths-filter@v3
        with:
          base: ${{ steps.commits.outputs.base }}
          ref: ${{ steps.commits.outputs.current }}
          filters: |
            a:
              - 'a/**'
            b:
              - 'b/**'
      - name: Print changed files
        run: |
          echo "Changed in 'a': ${{ steps.filter.outputs.a }}"
          echo "Changed in 'b': ${{ steps.filter.outputs.b }}"
  job-a:
    needs: changes
    if: ${{ needs.changes.outputs.a == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "A"

  job-b:
    needs: changes
    if: ${{ needs.changes.outputs.b == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "B"
