on: deployment_status
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      a: ${{ steps.filter.outputs.a }}
      b: ${{ steps.filter.outputs.b }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Determine base and ref for paths-filter
        id: commits
        run: |
          branch="${{ github.event.deployment.ref }}"
          deployed_sha="${{ github.event.deployment.sha }}"
          if [ "$branch" = "main" ]; then
            base=$(git rev-parse main^)
            ref=$(git rev-parse main)
          else
            base=$(git rev-parse origin/main)
            ref=$deployed_sha
          fi
          echo "base=$base" >> $GITHUB_OUTPUT
          echo "ref=$ref" >> $GITHUB_OUTPUT
      - name: Paths Filter (dorny/paths-filter)
        id: filter
        uses: dorny/paths-filter@v3
        with:
          base: ${{ steps.commits.outputs.base }}
          ref: ${{ steps.commits.outputs.ref }}
          filters: |
            a:
              - 'a/**'
            b:
              - 'b/**'
      - name: Print changed files
        run: |
          echo "Changed in 'a': ${{ steps.filter.outputs.a }}"
          echo "Changed in 'b': ${{ steps.filter.outputs.b }}"
  job-a:
    needs: changes
    if: ${{ needs.changes.outputs.a == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "A"

  job-b:
    needs: changes
    if: ${{ needs.changes.outputs.b == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "B"
